apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
{{ if .Values.global.dependencies.database.ssl.ca }}
  database-ssl-ca: |-
{{ .Values.global.dependencies.database.ssl.ca | indent 4 }}
{{ end }}
