apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      App: Metabase
  template:
    metadata:
      labels:
        App: Metabase
    spec:
      containers:
        - name: metabase
          image: metabase/metabase:v0.44.6
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: {{ .Values.environment }}
            - name: MB_DB_TYPE
              value: postgres
            - name: MB_DB_DBNAME
              value: {{ required "database.name is required" .Values.global.dependencies.database.name }}
            - name: MB_DB_PORT
              value: "{{ required "database.port is required" .Values.global.dependencies.database.port }}"
            - name: MB_DB_USER
              value: {{ required "database.user is required" .Values.global.dependencies.database.user }}
            - name: MB_DB_PASS
              value: {{ required "database.password is required" .Values.global.dependencies.database.password }}
            - name: MB_DB_HOST
              value: {{ required "database.host is required" .Values.global.dependencies.database.host }}
{{ if .Values.global.dependencies.database.ssl.ca }}
            - name: PGSSLMODE
              value: "require"
          volumeMounts:
            - name: database-ssl-ca
              mountPath: /etc/ssl/certs/database-ssl-ca.pem
              subPath: database-ssl-ca.pem
              readOnly: false
      volumes:
        - name: database-ssl-ca
          configMap:
            name: config
            items:
              - key: database-ssl-ca
                path: database-ssl-ca.pem
{{end}}
