apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: torus-metabase
  namespace: {{ .Release.Namespace }}
spec:
  numberOfInstances: 1
  postgresql:
    version: "13"
  volume:
    size: 1Gi
  teamId: "torus"
  users:
    metabase:
      - superuser
      - createdb
  databases:
    metabase: metabase
