apiVersion: v1
kind: Secret
metadata:
  name: secrets
  labels:
    app: chatwoot
data:
  REDIS_PASSWORD: {{ required "redis.password is required" .Values.global.dependencies.redis.password | b64enc | quote }}
  REDIS_URL: {{ printf "redis://:%s@%s:%d"
    .Values.global.dependencies.redis.password
    .Values.global.dependencies.redis.host
    int(.Values.global.dependencies.redis.port) | b64enc | quote }}
  {{- range $key, $value := .Values.env}}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
  {{- end }}
