apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatwoot
  labels:
    app: chatwoot
    role: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatwoot
      role: web
  template:
    metadata:
      labels:
        app: chatwoot
        role: web
    spec:
      containers:
        - image: chatwoot/chatwoot:v2.10.0-ce
          name: chatwoot
          ports:
            - containerPort: 3000
          args:
            - bundle
            - exec
            - rails
            - s
            - -p
            - "3000"
            - -b
            - 0.0.0.0
          command:
            - docker/entrypoints/rails.sh
          envFrom:
            - secretRef:
                name: secrets
          env:
            - name: POSTGRES_HOST
              value: torus-chatwoot
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USERNAME
              value: chatwoot
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chatwoot.torus-chatwoot.credentials.postgresql.acid.zalan.do
                  key: password
            - name: POSTGRES_DATABASE
              value: chatwoot
            - name: REDIS_HOST
              value: {{ required "redis.host is required" .Values.global.dependencies.redis.host | quote }}
            - name: REDIS_PORT
              value: {{ required "redis.port is required" .Values.global.dependencies.redis.port | quote }}
