apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatwoot-worker
  labels:
    app: chatwoot
    role: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatwoot
      role: worker
  template:
    metadata:
      labels:
        app: chatwoot
        role: worker
    spec:
      containers:
        - name: chatwoot-worker
          image: chatwoot/chatwoot:v2.10.0-ce
          args:
            - bundle
            - exec
            - sidekiq
            - -C
            - config/sidekiq.yml
          envFrom:
            - secretRef:
                name: secrets
          env:
            - name: POSTGRES_HOST
              value: {{ required "database.host is required" .Values.global.dependencies.database.host | quote }}
            - name: POSTGRES_PORT
              value: {{ required "database.port is required" .Values.global.dependencies.database.port | quote }}
            - name: POSTGRES_USERNAME
              value: {{ required "database.user is required" .Values.global.dependencies.database.user | quote }}
            - name: POSTGRES_DATABASE
              value: "{{ required "context.id is required" .Values.global.context.id }}-db"
            - name: REDIS_HOST
              value: {{ required "redis.host is required" .Values.global.dependencies.redis.host | quote }}
            - name: REDIS_PORT
              value: {{ required "redis.port is required" .Values.global.dependencies.redis.port | quote }}
{{ if .Values.global.dependencies.database.ssl.ca }}
            - name: PGSSLMODE
              value: "require"
          volumeMounts:
            - name: database-ssl-ca
              mountPath: /etc/ssl/certs/database-ssl-ca.pem
              subPath: database-ssl-ca.pem
              readOnly: false
      volumes:
        - name: database-ssl-ca
          configMap:
            name: config
            items:
              - key: database-ssl-ca
                path: database-ssl-ca.pem
{{end}}
