global:
  context:
    id: ""
  dependencies:
    postgres:
      pgbackrest_secret: ""
  provider: ""

environment: prod
postgresVersion: 14

s3:
  bucket: ""
  endpoint: ""
  region: ""
gcs:
  bucket: ""
