apiVersion: apps/v1
kind: Deployment
metadata:
  name: flagsmith
spec:
  replicas: 1
  selector:
    matchLabels:
      App: Flagsmith
  template:
    metadata:
      labels:
        App: Flagsmith
    spec:
      containers:
        - name: flagsmith
          image: flagsmith/flagsmith:latest
          ports:
            - containerPort: 8000
            - containerPort: 5432
          env:
            - name: ENV
              value: prod
            - name: DJANGO_ALLOWED_HOSTS
              value: "*"
            - name: DISABLE_INFLUXDB_FEATURES
              value: "true"
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: flagsmith.torus-flagsmith.credentials.postgresql.acid.zalan.do
                key: username
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: flagsmith.torus-flagsmith.credentials.postgresql.acid.zalan.do
                key: password
          - name: DATABASE_URL
            value: "{{ printf "postgres://$(DATABASE_USER):$(DATABASE_PASSWORD)@torus-flagsmith:5432/flagsmith-db" }}"
          resources:
            limits:
              cpu: "0.5"
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 50Mi
