apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: torus-flagsmith
  namespace: {{ .Release.Namespace }}
spec:
  numberOfInstances: 1
  postgresql:
    version: "13"
  volume:
    size: 1Gi
  teamId: "torus"
  users:
    flagsmith:
      - superuser
      - createdb
  databases:
    flagsmithdb: flagsmith
