global:
  context:
    id: ""

environment: production
url: ""

mysql-innodbcluster:
  serverInstances: 2
  routerInstances: 1
  tls:
    useSelfSigned: true
  credentials:
    root:
      user: ghost
      password: {{ randAlphaNum 24 | b64enc }}
