name: build-and-deploy
run-name: Build & Deploy
on:
  push:
    branches:
      - master
jobs:
  helm-repository:
    name: Helm Repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        id: install
      - name: Package Helm charts
        run: |
          for chart in $(find . -type f -regex '^.*\/helm\/[^/]*\/Chart\.yaml$');                   \
          do                                                                                        \
            helm package $(dirname $chart);                                                         \
          done
        shell: bash
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: |
          for pkg in $(find . -type f -path  '^.*\/helm\/[^/]*\/[^/]*\.tgz$');                      \
          do                                                                                        \
            aws s3 cp $pkg s3://charts.cloudtorus                                                   \
              --endpoint=https://nyc3.digitaloceanspaces.com;                                       \
          done
        shell: bash
