name: helm-repository
run-name: Helm Repository
on:
  push:
    branches:
      - master
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: ${{ secrets.GITHUB_TOKEN }}
        id: install
      - name: Package Helm charts
        run: |
          for chart in $(find . -name "helm/Chart.yaml")
          do
            helm package $(dirname chart)
          end
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: |
          for pkg in $(find . -name "helm/*.tgz")
          do
            aws s3 cp pkg s3://charts.cloudtorus --endpoint=https://nyc3.digitaloceanspaces.com
          end
